/**
 * Modelli email del CICLO DI VITA / marketing (45), copy da `marketing/Metabole_Email_Ciclo_Vita.md`.
 * Editabili dal backoffice (Modelli email); inviati via Brevo quando l'innesco scatta.
 * Il seed li crea SOLO se assenti (non sovrascrive le modifiche dell'admin).
 */
export const MARKETING_EMAIL_TEMPLATES: { key: string; name: string; subject: string; bodyHtml: string }[] = [
  {
    "key": "welcome",
    "name": "Benvenuto",
    "subject": "Benvenuta in Metabole, {{nome}} 🌱",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">benvenuta in Metabole. Qui non troverai l'ennesima dieta uguale per tutti: costruiamo un <strong>percorso su misura per te</strong>, seguito da una coach e da un nutrizionista veri, con l'aiuto della nostra assistente Gaia.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Come funziona, in tre passi:</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\"><strong>1.</strong> Rispondi a qualche domanda sul tuo obiettivo e i tuoi gusti.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\"><strong>2.</strong> Ti proponiamo il percorso alimentare più adatto, con coach e nutrizionista dedicati.</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\"><strong>3.</strong> Ogni giorno hai il tuo menu; tu ci dici com'è andata e il percorso si adatta a te.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Nessuna fame, nessun conteggio ossessivo: solo cibo buono, pensato per te.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Completa il tuo profilo →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché ti sei registrata a Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "profilo_pronto",
    "name": "Il tuo profilo è pronto",
    "subject": "{{nome}}, ecco il percorso pensato per te",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">abbiamo letto con attenzione le tue risposte e costruito qualcosa di pensato davvero su di te.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\"><strong>Percorso consigliato: {{piano}}</strong><br>Scelto tra i nostri percorsi in base a ciò che ci hai raccontato dei tuoi obiettivi e dei tuoi gusti.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\"><strong>Il tuo team dedicato</strong><br>🥗 Nutrizionista {{nutrizionista}} — costruisce e valida il tuo menu.<br>💬 Coach {{coach}} — ti segue giorno per giorno e ti motiva.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">È tutto pronto: manca solo il tuo \"sì\" per iniziare.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Attiva il tuo percorso →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Hai dubbi? Rispondi a questa email: ti risponde una persona vera.<br><br>A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché hai completato il tuo profilo Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "piano_domani",
    "name": "Il tuo piano inizia domani",
    "subject": "{{nome}}, si parte domani! La lista spesa 🛒",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">ci siamo: <strong>domani inizia il tuo percorso {{piano}}</strong>. Per arrivare pronta, ti abbiamo preparato la lista della spesa dei tuoi primi giorni, già pensata sui tuoi menu.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\"><strong>Come funziona da domani:</strong></p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">• Ogni mattina trovi il menu del giorno nell'app.<br>• Ogni 2 giorni ti chiediamo le tue misure: è il segnale che fa adattare il percorso a te.<br>• {{coach}} è a un messaggio di distanza, e Gaia ti guida passo passo.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Un consiglio: prepara stasera ciò che ti serve per la colazione. Iniziare bene la mattina fa la differenza.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Apri la lista della spesa →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">In bocca al lupo — siamo con te.<br>{{coach}} e il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché stai per iniziare il tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "profilo_incompleto",
    "name": "Profilo incompleto",
    "subject": "Ti manca solo un minuto, {{nome}}",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">hai iniziato a raccontarci di te, ma non hai ancora finito. Bastano un paio di minuti per completare il profilo e ricevere il <strong>percorso pensato su di te</strong>, con coach e nutrizionista dedicati.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Riprendi da dove hai lasciato: le tue risposte sono già salvate.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Completa il profilo →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché ti sei registrata a Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "cart_1h",
    "name": "Carrello +1h",
    "subject": "{{nome}}, il tuo percorso {{piano}} ti aspetta",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">hai scelto il percorso <strong>{{piano}}</strong> ma non hai completato l'attivazione. Nessun problema: è tutto salvato, riprendi in un clic.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ti aspettano il tuo menu su misura, la coach {{coach}} e il nutrizionista {{nutrizionista}}.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Completa l'attivazione →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Se qualcosa non è chiaro, rispondi a questa email: c'è una persona vera dall'altra parte.<br><br>A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché hai scelto un percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "cart_24h",
    "name": "Carrello +24h (obiezioni)",
    "subject": "\"Ci ho già provato e non ha funzionato\"",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">se hai esitato, forse ci sei già passata: diete uguali per tutti, fame, e alla fine si molla.</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Con Metabole è diverso per un motivo semplice: <strong>il percorso si adatta a te</strong>, non tu alla dieta. Niente fame, niente conteggi ossessivi. E non sei sola: una coach ti segue ogni giorno, un nutrizionista valida ogni menu.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"margin:8px 0 16px 0;\"><tr><td style=\"padding:16px 18px;background-color:#f4f7f2;border-radius:8px;\"><p style=\"margin:0;font-size:15px;line-height:1.6;color:#3d5a45;font-style:italic;\">\"Non pensavo di poter mangiare così e sentirmi finalmente seguita. Per la prima volta non mi sono sentita a dieta.\" — Giulia</p></td></tr></table><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:16px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Inizia il tuo percorso →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché hai scelto un percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "cart_72h",
    "name": "Carrello +72h (incentivo)",
    "subject": "{{nome}}, un pensiero per iniziare 🎁",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">vogliamo aiutarti a fare il primo passo. Se attivi il tuo percorso {{piano}} <strong>entro 48 ore</strong>, la prima settimana di coaching è inclusa: un piccolo pensiero per cominciare con qualcuno al tuo fianco.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">È il momento giusto per iniziare a stare bene, con calma e senza pressioni.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Attiva ora e approfitta →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:14px;line-height:1.6;color:#6b655e;\">Il pensiero è valido per le prossime 48 ore.</p><p style=\"margin:16px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché hai scelto un percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "nurture_1",
    "name": "Perché non è una dieta",
    "subject": "Perché Metabole non è una dieta",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">le diete falliscono perché chiedono a <strong>te</strong> di adattarti a loro. Noi facciamo il contrario: il menu si adatta a te — ai tuoi gusti, ai tuoi tempi, a come reagisce il tuo corpo — sotto la guida di un nutrizionista.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Niente fame, niente conteggi. Solo cibo buono che funziona per te. Non è una dieta, è un percorso.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Scopri il tuo percorso →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché fai parte della community Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "nurture_2",
    "name": "Il tuo team",
    "subject": "Non sei sola: il tuo team Metabole",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">in Metabole non ti lasciamo con un'app e basta. Hai una <strong>coach</strong> che ti segue giorno per giorno e ti motiva, e un <strong>nutrizionista</strong> che costruisce e valida il tuo menu.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Gaia, la nostra assistente, ti guida passo passo. Le persone fanno la differenza, soprattutto nei giorni in cui serve un po' di spinta.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Inizia con il tuo team →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché fai parte della community Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "nurture_3",
    "name": "Storie come la tua",
    "subject": "Storie come la tua",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">a volte aiuta sapere che qualcuna è già partita da dove sei tu adesso.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"margin:8px 0 16px 0;\"><tr><td style=\"padding:16px 18px;background-color:#f4f7f2;border-radius:8px;\"><p style=\"margin:0;font-size:15px;line-height:1.6;color:#3d5a45;font-style:italic;\">\"Dopo la gravidanza pensavo fosse impossibile ritrovare il mio equilibrio. Con un menu che cambiava con me, e qualcuno con cui parlarne, ci sono riuscita a modo mio.\" — Marta</p></td></tr></table><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ognuna è partita da un momento diverso; tutte hanno trovato un modo sostenibile, senza rinunce. Il prossimo passo può essere il tuo.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:16px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Comincia oggi →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché fai parte della community Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "nurture_4",
    "name": "Pronta quando lo sei tu",
    "subject": "Ci siamo quando decidi tu, {{nome}}",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">nessuna fretta e nessuna pressione. Quando ti va, il tuo percorso <strong>{{piano}}</strong> è pronto a partire, con coach e nutrizionista già dalla tua parte.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Se hai una domanda, rispondi a questa email: ti risponde una persona vera.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Attiva quando vuoi →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché fai parte della community Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "obiezione_prezzo",
    "name": "Obiezione prezzo",
    "subject": "Un piccolo investimento su di te, {{nome}}",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">capisco l'esitazione. Ma pensa a cosa c'è dentro {{piano}}: un percorso su misura, una <strong>coach</strong> e un <strong>nutrizionista</strong> sempre con te — spesso meno di quanto spendi per un caffè al giorno.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">È un investimento su di te, sulla tua energia, sul tuo benessere. E se hai un dubbio, parliamone: rispondi a questa email.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Parla con noi →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché hai mostrato interesse per un percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "onb_g1",
    "name": "Onboarding G1 - Il tuo primo giorno",
    "subject": "Benvenuta nel tuo primo giorno, {{nome}}!",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">oggi si comincia! Nell'app trovi il <strong>menu del giorno</strong> in Home; nella sezione Contatti ci sono la tua coach {{coach}} e Gaia, sempre a un messaggio di distanza.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Un consiglio: parti dalla colazione e prenditela con calma. Non serve fare tutto perfetto, serve solo iniziare.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Apri l'app →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Buon primo giorno,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché hai iniziato il tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "onb_g2",
    "name": "Onboarding G2 - Il primo check-in",
    "subject": "Il tuo primo check-in, {{nome}}",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">ogni 2 giorni ti chiediamo le tue misure: è il <strong>segnale</strong> che permette al percorso di adattarsi a te.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Niente ansia da bilancia — è solo il modo in cui capiamo cosa funziona meglio per il tuo corpo. Bastano pochi secondi.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Fai il check-in →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "onb_g4",
    "name": "Onboarding G4 - Sostituzioni e gusti",
    "subject": "Un piatto non ti va? Cambialo",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">se un piatto non ti piace o non lo mangi, dillo nell'app: il percorso ti propone subito un'<strong>alternativa</strong>.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Più ci dici cosa ami e cosa eviti, più il tuo menu diventa davvero tuo. Il percorso si adatta a te, non il contrario.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Aggiorna i tuoi gusti →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "onb_g7",
    "name": "Onboarding G7 - La tua prima settimana",
    "subject": "Una settimana insieme, {{nome}} 🌿",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">sette giorni fa hai deciso di prenderti cura di te, e sei ancora qui. Hai già fatto la parte più difficile: iniziare.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">È così che nascono i risultati che durano: <strong>un passo alla volta</strong>. {{coach}} è fiera di te — continua così.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Vedi i tuoi progressi →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">{{coach}}, la tua coach</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "feedback_ricette",
    "name": "Feedback ricette",
    "subject": "Com'era il tuo menu, {{nome}}?",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">un piatto ti è piaciuto tantissimo? O proprio no? Dillo con un tocco nell'app.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Più valuti, più il percorso <strong>impara</strong> cosa proporti e diventa più tuo. Bastano pochi secondi.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Valuta i piatti →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Grazie,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "valore_settimanale",
    "name": "Consiglio della settimana",
    "subject": "Il consiglio della settimana 🍋",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">il consiglio di questa settimana da {{coach}}: tieni sempre a portata di mano qualcosa di sano e già pronto. Nei momenti di fretta, avere una scelta buona a disposizione cambia la giornata.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Sul blog trovi una ricetta semplice e nel tuo stile, con pochi ingredienti e tanto gusto. Piccole abitudini, grandi risultati.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Scopri la ricetta →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché fai parte della community Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "riattiva_dropout",
    "name": "Riattivazione dropout",
    "subject": "Ci sei, {{nome}}? Ripartiamo insieme",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">ti abbiamo persa di vista in questi giorni — capita, la vita è piena di cose. Nessun giudizio.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Il tuo percorso è ancora qui, pronto a riprenderti da dove eri. {{coach}} è a un messaggio di distanza se vuoi ripartire con calma, un passo alla volta.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Riapri l'app →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ti aspetto,<br>{{coach}}, la tua coach</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "referral",
    "name": "Porta un'amica",
    "subject": "Porta un'amica in Metabole",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">se Metabole ti sta aiutando, forse può aiutare anche una persona a cui vuoi bene.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Invitala: c'è un <strong>vantaggio per entrambe</strong>. Il benessere è più bello condiviso, e affrontare un percorso in due lo rende più leggero.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Invita un'amica →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Grazie,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "ev_peso_ok",
    "name": "Obiettivo raggiunto",
    "subject": "{{nome}}, ce l'hai fatta 🎉",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">oggi è un giorno speciale: <strong>hai raggiunto il tuo obiettivo</strong>. Non è stato un colpo di fortuna — è il risultato della tua costanza, un giorno dopo l'altro.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Goditi questo traguardo. E se vuoi, parliamo di come mantenere ciò che hai conquistato: la modalità mantenimento è il modo migliore per non tornare indietro.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Scopri il mantenimento →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Brava davvero.<br>{{coach}}, la tua coach</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "ev_primo",
    "name": "Primo risultato",
    "subject": "Il primo passo è fatto, {{nome}} 🌱",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">i primi risultati stanno arrivando, e sono i più importanti perché ti dicono una cosa: <strong>funziona, per te</strong>.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Continua così, un giorno alla volta. Il bello deve ancora venire.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Vedi il tuo percorso →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">{{coach}}, la tua coach</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "ev_meta",
    "name": "Metà strada",
    "subject": "Sei a metà strada, {{nome}} 💪",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">metà del cammino è dietro di te. Il bello è che ora <strong>sai di poterlo fare</strong>.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">{{coach}} è con te per la seconda parte, con lo stesso passo tranquillo che ti ha portata fin qui.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Continua il percorso →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">{{coach}}, la tua coach</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "ev_costanza",
    "name": "Costanza / streak",
    "subject": "{{nome}}, che costanza! 🔥",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">hai completato diversi check-in di fila: la <strong>costanza</strong> è la tua arma migliore, e la stai usando benissimo.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Piccolo grande traguardo: continua a prenderti cura di te, un giorno alla volta.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Vedi i tuoi progressi →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">{{coach}}, la tua coach</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "ev_plateau",
    "name": "Plateau",
    "subject": "Il corpo lavora anche a bilancia ferma",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">a volte il corpo si assesta per qualche giorno: è normale, si sta abituando. <strong>Non è un passo indietro.</strong></p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Il nutrizionista {{nutrizionista}} sta già ritoccando il tuo percorso per rimetterti in moto. Fidati del processo — e di noi.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Scrivi alla coach →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">{{coach}}, la tua coach</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "ev_morale",
    "name": "Giornata storta",
    "subject": "Una giornata storta non cancella i progressi",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">capita a tutti una giornata no. <strong>Non definisce il tuo percorso</strong>: domani si riparte, con calma.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Per oggi, il menu è pensato per coccolarti un po' senza farti perdere la strada. Sono qui se hai bisogno.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Scrivi alla coach →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Un abbraccio,<br>{{coach}}, la tua coach</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "ev_misure",
    "name": "Reminder misure",
    "subject": "Un attimo per te, {{nome}}",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">per farti proseguire al meglio, ci servono le tue <strong>misure</strong> di questi due giorni: sono il segnale che fa adattare il percorso a te.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Bastano pochi secondi, e nessuna ansia da bilancia: è solo un modo per prenderti cura di te.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Inserisci le misure →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "ev_rientro",
    "name": "Rientro dopo pausa",
    "subject": "Bentornata, {{nome}} — ripartiamo con dolcezza",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">ben tornata! Nessuna corsa e nessun senso di colpa: ripartiamo con qualche giorno leggero, poi torniamo al ritmo.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Il tuo team ti riaccoglie <strong>da dove avevi lasciato</strong>: menu, storico e personalizzazione sono tutti qui.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Riprendi il percorso →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">{{coach}}, la tua coach</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "ev_compleanno",
    "name": "Compleanno",
    "subject": "Buon compleanno, {{nome}}! 🎂",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 24px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">oggi è la tua giornata: goditela senza pensieri. 🎂</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Prenderti cura di te è il regalo più bello che puoi farti — e noi siamo felici di farlo con te. Buon compleanno di cuore.</p><p style=\"margin:24px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Con affetto,<br>{{coach}} e il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "ev_anniversario",
    "name": "Anniversario percorso",
    "subject": "{{nome}}, un mese insieme 🌿",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">un mese fa hai deciso di prenderti cura di te. Da allora ne è successa di strada: nuove abitudini, più costanza, i primi risultati.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\"><strong>Grazie per la fiducia</strong> — il meglio deve ancora venire.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Vedi il tuo riepilogo →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">{{coach}} e il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "ev_pre_evento",
    "name": "Pre-evento",
    "subject": "Arriviamo pronte a {{evento}}, {{nome}}",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">manca poco a <strong>{{evento}}</strong>! Nei prossimi giorni il tuo menu diventa un po' più leggero e proteico, per farti arrivare al meglio senza stress.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ci pensiamo noi: tu goditi l'attesa. Il tuo team ha già adattato il percorso a questa occasione.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Vedi il piano pre-evento →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">{{coach}}, la tua coach</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "ev_mantenimento",
    "name": "Passaggio al mantenimento",
    "subject": "E ora, manteniamo ciò che hai conquistato",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">hai raggiunto il tuo obiettivo: bravissima. Da qui il percorso cambia scopo — <strong>difendere il risultato</strong>, senza rinunce.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Con menu pensati per mantenerti in equilibrio, continui a stare bene mantenendo ciò che hai costruito.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Attiva il mantenimento →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">{{coach}}, la tua coach</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "rin_t7",
    "name": "Rinnovo T-7",
    "subject": "{{nome}}, guarda quanta strada hai fatto",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">in queste settimane hai costruito qualcosa di importante: <strong>costanza, abitudini nuove e i primi risultati</strong>. Il tuo percorso {{piano}} sta per concludersi.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Continuare adesso è ciò che trasforma i risultati in qualcosa che resta. {{coach}} è pronta a proseguire con te.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Rinnova il tuo percorso →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">{{coach}}, la tua coach</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "rin_t3",
    "name": "Rinnovo T-3",
    "subject": "Non fermarti proprio ora, {{nome}}",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">il tuo percorso scade tra pochi giorni. Fermarsi ora significherebbe rinunciare allo slancio che hai costruito — e il bello arriva proprio con la <strong>continuità</strong>.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Se vuoi, puoi anche passare al piano più adatto a questa fase: parlane con {{coach}}, sceglierete insieme.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Continua il percorso →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">{{coach}}, la tua coach</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "rin_t1",
    "name": "Rinnovo T-1",
    "subject": "Il tuo percorso scade domani, {{nome}}",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">domani il tuo percorso {{piano}} si conclude. Rinnovando <strong>ora</strong> non perdi nulla: menu, storico, personalizzazione e il tuo team restano esattamente dove sono.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Vuoi parlarne prima? Rispondi a questa email: c'è una persona vera dall'altra parte.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Rinnova in un clic →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">{{coach}}, la tua coach</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "upsell",
    "name": "Upsell / cambio piano",
    "subject": "Un passo avanti per te, {{nome}}",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">stai andando bene, e forse è il momento di fare <strong>un passo in più</strong>: un piano più adatto a questa fase del tuo percorso.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ne parli con la tua coach {{coach}} e il nutrizionista {{nutrizionista}}, così scegli in serenità ciò che ti serve davvero adesso.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Scopri il piano →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei nel tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "wb_t3",
    "name": "Win-back T+3",
    "subject": "Riprendi da dove avevi lasciato, {{nome}}",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">il tuo percorso si è concluso qualche giorno fa, ma non abbiamo cancellato nulla: <strong>menu, storico e personalizzazione</strong> ti aspettano.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Bastano un paio di clic per ricominciare, con la tua coach {{coach}} di nuovo al tuo fianco.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Riattiva il percorso →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ti aspettiamo,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché hai avuto un percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "wb_t7",
    "name": "Win-back T+7 (novità)",
    "subject": "È cambiato qualcosa in Metabole",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">da quando ci siamo lasciati abbiamo aggiunto <strong>novità</strong> pensate proprio per rendere il percorso più semplice e su misura.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Se vuoi riprovare, ti accogliamo con un vantaggio di rientro. Ci farebbe piacere riaverti con noi.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Torna con noi →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché hai avuto un percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "wb_survey",
    "name": "Win-back survey",
    "subject": "Aiutaci a capire, {{nome}}",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">hai lasciato Metabole e ci dispiace. Ci aiuteresti con <strong>una sola domanda</strong>? Cosa ti ha fatto interrompere il percorso?</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Il tuo parere ci rende migliori — e la porta resta sempre aperta, quando vorrai.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Rispondi (1 domanda) →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Grazie,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché hai avuto un percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "wb_stagionale",
    "name": "Win-back stagionale",
    "subject": "È il momento giusto per ripartire",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">certi momenti dell'anno sono quelli in cui viene voglia di rimettersi in carreggiata. Se senti che è il tuo, <strong>ripartiamo insieme</strong>.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Con il percorso più adatto a questa stagione, senza pressioni e al tuo ritmo. Un nuovo inizio, con la stessa cura di sempre.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Riparti con noi →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché hai avuto un percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "tx_rinnovo_ok",
    "name": "Rinnovo confermato",
    "subject": "Rinnovo confermato — si continua! 🌿",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">il rinnovo è andato a buon fine: il tuo percorso {{piano}} continua senza interruzioni fino al <strong>{{data}}</strong>, con la tua coach {{coach}} e il nutrizionista {{nutrizionista}}.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Grazie per la fiducia. Si continua.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Continua il percorso →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Questa è una comunicazione di servizio legata al tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "tx_dunning",
    "name": "Pagamento fallito (dunning)",
    "subject": "Problema con il pagamento, {{nome}}",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">non siamo riusciti a completare il pagamento del tuo {{piano}}. Nessun problema: <strong>aggiorna il metodo di pagamento</strong> e riproviamo subito, così il percorso continua senza interruzioni.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Riproveremo comunque in automatico nei prossimi giorni.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Aggiorna il metodo →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Questa è una comunicazione di servizio legata al tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "tx_appuntamento",
    "name": "Promemoria appuntamento",
    "subject": "Il tuo appuntamento con {{nutrizionista}}",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">ti ricordiamo il tuo appuntamento in <strong>televisita</strong> con {{nutrizionista}}.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"margin:8px 0 16px 0;\"><tr><td style=\"padding:16px 18px;background-color:#f4f7f2;border-radius:8px;\"><p style=\"margin:0;font-size:16px;line-height:1.6;color:#3d5a45;\"><strong>Data e ora:</strong> {{data}}</p></td></tr></table><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Collegati dal link qui sotto qualche minuto prima. Se devi spostarlo, avvisa la tua coach {{coach}}.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Vai alla televisita →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Questa è una comunicazione di servizio legata al tuo percorso Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "repermission",
    "name": "Re-opt-in consenso",
    "subject": "Vuoi restare in contatto con Metabole?",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">teniamo alla tua privacy. Vuoi continuare a ricevere consigli di benessere, ricette e novità da Metabole?</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Con un clic <strong>confermi</strong> il consenso. Se non confermi, non ti scriveremo più (salvo le comunicazioni di servizio).</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Sì, restiamo in contatto →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché in passato ti sei iscritta a Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  },
  {
    "key": "preferenze",
    "name": "Centro preferenze",
    "subject": "Gestisci le tue preferenze email",
    "bodyHtml": "<div style=\"margin:0;padding:0;background-color:#f4f1ea;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f4f1ea;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><table role=\"presentation\" width=\"560\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:560px;width:100%;background-color:#ffffff;border-radius:12px;font-family:Arial,Helvetica,sans-serif;\"><tr><td style=\"padding:32px 32px 8px 32px;\"><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Ciao {{nome}},</p><p style=\"margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">qui decidi tu: quali email ricevere (consigli, novità, promemoria) e con quale <strong>frequenza</strong>.</p><p style=\"margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#2f2a26;\">Preferisci solo l'essenziale? Nessun problema. La tua casella, le tue regole.</p><table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:24px 0;\"><tr><td align=\"center\" bgcolor=\"#0a7d55\" style=\"border-radius:8px;\"><a href=\"{{link}}\" style=\"display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:8px;\">Aggiorna le preferenze →</a></td></tr></table><p style=\"margin:8px 0 0 0;font-size:16px;line-height:1.6;color:#2f2a26;\">A presto,<br>il team Metabole</p></td></tr><tr><td style=\"padding:16px 32px 28px 32px;border-top:1px solid #eeeae2;\"><p style=\"margin:0;font-size:12px;line-height:1.5;color:#9a948d;\">Ricevi questa email perché sei iscritta alle comunicazioni Metabole. <a href=\"{{link_preferenze}}\" style=\"color:#9a948d;text-decoration:underline;\">Gestisci le tue preferenze</a>.</p></td></tr></table></td></tr></table></div>"
  }
];
