/**
 * Le frasi di Gaia — card "LA FRASE DI OGGI" in Home.
 *
 * Prima erano SEI, scelte con `giorno_del_mese % 6`: la stessa frase per tutte le clienti,
 * lo stesso ciclo cinque volte al mese, e una ripetizione due giorni di fila ogni volta che
 * un mese di 31 giorni finiva (31 % 6 === 1 % 6). Ora sono 360, scelte in modo che ogni
 * cliente veda una sequenza diversa.
 *
 * COME VIENE SCELTA (`fraseDelGiorno`)
 * Non si usa `Math.random()`: l'etichetta dice "la frase di OGGI", quindi deve restare la
 * stessa per tutto il giorno — con un random vero cambierebbe a ogni ritorno in Home, e
 * l'animazione a macchina da scrivere ripartirebbe ogni volta. La scelta è invece
 * deterministica su (utente, giorno):
 *
 *   indice = (partenza_utente + numero_del_giorno * passo_utente) % 360
 *
 * `passo` è preso fra numeri **coprimi con 360**: questo garantisce che la sequenza tocchi
 * tutte e 360 le frasi prima di ripeterne una, cioè nessuna ripetizione per quasi un anno.
 * `partenza` e `passo` derivano da bit diversi dell'hash dell'id utente, così due clienti
 * lo stesso giorno leggono quasi sempre frasi diverse e in ordine diverso.
 *
 * REGOLE DEI TESTI (da rispettare aggiungendone di nuove)
 *  - niente promesse di risultati, numeri, tempi o garanzie;
 *  - niente claim medici o terapeutici: qui non si fa clinica;
 *  - niente colpa, niente vergogna, niente "cibo proibito" o "sgarro";
 *  - niente aspetto fisico come misura del valore della persona;
 *  - **niente aggettivi di genere riferiti a chi legge**: l'app è usata anche da uomini
 *    ("brava", "stanca", "sicuro" vanno riformulati in modo neutro);
 *  - massimo ~80 caratteri: oltre, l'animazione di `TypeText` (62 ms per carattere)
 *    diventa più lenta di quanto una card sopporti.
 *
 * L'ordine dell'array è **volutamente mescolato**: le frasi nascono raggruppate per tema, e
 * siccome la selezione avanza a passi fissi dentro l'array, con i temi in blocco una cliente
 * leggerebbe più giorni di fila sullo stesso argomento.
 */
export const FRASI_GAIA: string[] = [
  'Le cose non riuscite insegnano più di quelle riuscite.',
  'L\'energia del pomeriggio dipende da com\'è andato il pranzo.',
  'A volte non è fame, è stanchezza.',
  'L\'appetito cambia da un giorno all\'altro, ed è normale.',
  'Non serve annunciare a tutti cosa stai facendo.',
  'Nessun alimento da solo decide come va il percorso.',
  'Dì di no a qualcosa, oggi: guadagni tempo.',
  'Le cose che durano si costruiscono lentamente.',
  'La differenza tra voglia e bisogno cambia tutto.',
  'Sii gentile con te: stai già facendo tanto.',
  'Il girovita è un dato paziente: cambia piano.',
  'Il congelatore è un alleato, non un ripostiglio.',
  'Il piano B non è un fallimento: è un piano.',
  'Una cena fuori non sposta niente.',
  'Farsi aiutare con la spesa è legittimo: è lavoro anche quello.',
  'Il pranzo portato da casa è il migliore che c\'è.',
  'Non c\'è niente da farsi perdonare.',
  'Fame nervosa: prima riconoscerla, poi decidere.',
  'Fai pace con la giornata di ieri.',
  'Anche pulire casa è movimento.',
  'Un alleato in casa vale più di dieci propositi.',
  'Bere prima di mangiare aiuta più di quanto sembri.',
  'Metti giù il telefono per dieci minuti.',
  'Se la stanchezza chiede zuccheri, in realtà chiede riposo.',
  'Contare i passi aiuta, ma camminare aiuta di più.',
  'Se piove, cammina dentro casa. Vale lo stesso.',
  'Scrivere quello che pesa lo rende più piccolo.',
  'Le abitudini si vedono dopo, non subito.',
  'Il cibo non è una ricompensa né una punizione.',
  'Se dopo mangiato arriva il sonno, il pasto era troppo.',
  'Anche le tisane contano.',
  'Rendi facile quello che vuoi fare e difficile il resto.',
  'Trova qualcuno con cui camminare: dura di più.',
  'Il corpo parla piano: bisogna fare silenzio per sentirlo.',
  'La strada si vede meglio guardando indietro.',
  'Oggi non è andata: domani c\'è di nuovo.',
  'Le pause fanno parte del cammino.',
  'Le regole troppo strette si rompono da sole.',
  'Tieni la bottiglia dove la vedi.',
  'Un antipasto condiviso è già una scelta.',
  'Il primo boccone è il più buono: quelli in mezzo, meno.',
  'Non esistono cibi proibiti, esistono le quantità.',
  'Il peso di un giorno non è un verdetto.',
  'Ascolta lo stomaco, non l\'orologio.',
  'Tieni sempre qualcosa di pronto per le sere storte.',
  'Parlati come parleresti a chi ti vuole bene.',
  'Ogni ripetizione rende la prossima più facile.',
  'Il periodo del mese si vede anche sulla bilancia.',
  'Le vacanze finiscono, le abitudini restano.',
  'Anche fuori casa, l\'acqua è gratis.',
  'Ogni scelta piccola conta più di quanto sembri.',
  'Non serve fare tutto: serve fare qualcosa.',
  'Vai a dormire quando hai sonno, non quando finisce la serie.',
  'Un bicchiere a ogni pasto: è già metà del lavoro.',
  'Il forno lavora mentre tu fai altro.',
  'Un buon olio a crudo cambia la cena.',
  'Un pasto lento sazia più di un pasto abbondante.',
  'Ogni stagione ha i suoi alimenti migliori: approfittane.',
  'Un pensiero fisso si scioglie camminando.',
  'Ansia e fame si somigliano: impara a distinguerle.',
  'Cammina mentre telefoni.',
  'Il traguardo si sposta, la strada resta la stessa.',
  'Se non sai da dove iniziare, inizia dalla più piccola.',
  'Fermati un minuto prima di rispondere alla giornata.',
  'La calma non è un lusso, è manutenzione.',
  'Mangiare bene non vuol dire mangiare triste.',
  'Piccolo e possibile batte grande e rimandato.',
  'Lo stress si sente anche a tavola.',
  'Anche oggi hai aggiunto un mattone.',
  'Non serve motivazione per una cosa che fai da sempre.',
  'Al ristorante si può mangiare bene: basta scegliere.',
  'Mangiare fuori non rompe niente.',
  'La sete arriva tardi: bevi prima di sentirla.',
  'Le giornate no servono a riconoscere quelle sì.',
  'Una giornata storta non annulla niente.',
  'Se ti manca un ingrediente, sostituiscilo: il menu regge.',
  'Comincia con qualcosa di così piccolo da non poter fallire.',
  'Ricominciare non è tornare indietro.',
  'Segnare quello che fai lo rende reale.',
  'Il riposo non è tempo perso.',
  'Chi misura capisce, chi indovina si arrabbia.',
  'Se è pronto si mangia, se è da preparare si rimanda.',
  'Torna al ritmo appena puoi, senza penitenze.',
  'Se la giornata è pesante, alleggerisci il resto.',
  'Bevi piano, ma bevi spesso.',
  'Il movimento non deve far male per funzionare.',
  'Le domande non sono mai banali.',
  'Il corpo chiede varietà: dagliela.',
  'Meglio poco tutti i giorni che tanto una volta ogni tanto.',
  'Le scale al posto dell\'ascensore, oggi.',
  'Meno cose in dispensa, meno decisioni da prendere.',
  'A volte non è fame, è noia.',
  'Domani è un altro giorno per fare la stessa cosa buona.',
  'La testa ha bisogno di pause quanto il corpo.',
  'Fermarsi appena sazi è un allenamento.',
  'Assaggia davvero il primo boccone.',
  'Comincia la giornata con un bicchiere.',
  'Le misure di oggi servono alle scelte di domani.',
  'Il pranzo di lavoro non deve essere una prova.',
  'La pancia gonfia non è grasso: è solo oggi.',
  'Le spezie fanno il lavoro che credevi facesse il sale.',
  'Il corpo si prende i suoi tempi, e non li contratta.',
  'Un pranzo in compagnia nutre due volte.',
  'Non si può rendere al massimo tutti i giorni.',
  'Puoi anche dire sì: è una scelta come un\'altra.',
  'Non aspettare di avere voglia: comincia e la voglia arriva.',
  'Le abitudini sono più forti della volontà.',
  'Il corpo è fatto per muoversi, non per stare fermo.',
  'Il gusto si riabitua: dagli qualche settimana.',
  'Un giorno tutto questo sarà normale.',
  'Chi va piano arriva lo stesso.',
  'Prepara la verdura appena torni: poi la usi.',
  'Anche oggi puoi imparare qualcosa sul tuo corpo.',
  'Parcheggia lontano: sono passi regalati.',
  'Non tutto si risolve oggi.',
  'Un allenamento breve fatto batte uno lungo saltato.',
  'Dormire poco fa venire fame il giorno dopo.',
  'In primavera è più facile ricominciare a camminare.',
  'Una stanza fresca e buia vale più di tanti rimedi.',
  'Domani comincia da stasera.',
  'Il corpo non è lineare, la bilancia nemmeno.',
  'Ogni giorno è un punto di partenza valido.',
  'Sentire la fame prima di mangiare è un buon segno.',
  'Al buffet, fai un giro prima di prendere il piatto.',
  'Bevi, respira, muoviti: il resto viene.',
  'Fatto è meglio di perfetto.',
  'Chiedere come è cucinato non è maleducazione.',
  'La bilancia dice un numero, non come stai.',
  'Un gesto ripetuto smette di essere una decisione.',
  'Il numero non decide che giornata sarà.',
  'Bere di più è la prima cosa che si sente.',
  'Chiudi la giornata con una cosa che ti piace.',
  'Sei tu che porti avanti questo percorso, non l\'app.',
  'I vestiti raccontano cose che il numero non dice.',
  'Il tuo percorso è tuo: puoi adattarlo.',
  'Ripetere è più utile che aumentare.',
  'La fretta non è mai stata una buona compagna di viaggio.',
  'Il peso cambia da un giorno all\'altro: guarda le settimane.',
  'Mastica di più: il resto viene da sé.',
  'Sette ore non sono un lusso.',
  'Meglio una regola sola che dieci buone intenzioni.',
  'Uno spuntino previsto vale più di uno spuntino di scorta.',
  'Porta con te qualcosa da sgranocchiare, per sicurezza.',
  'Se una cosa non funziona da un mese, cambiala.',
  'Il silenzio, ogni tanto, è la cosa più nutriente che c\'è.',
  'Un imprevisto si gestisce, non si subisce.',
  'Parlare con qualcuno non è una debolezza.',
  'Ogni misura registrata è un pezzo di storia in più.',
  'Chi ti vuole bene non ti mette in difficoltà a tavola.',
  'Un imprevisto non è un fallimento.',
  'Le cose buone si mangiano piano.',
  'La severità non è disciplina.',
  'La fame vera aspetta, la voglia passa.',
  'Guarda la direzione, non il singolo punto.',
  'Cucinare non deve essere complicato per essere buono.',
  'Meno sale non vuol dire meno sapore.',
  'Il bicchiere vuoto sul tavolo è un promemoria.',
  'Ricomincia da dove sei, non da dove volevi essere.',
  'Una lista in tasca vale più di mille buoni propositi.',
  'Se lo mangi, mangialo con gusto.',
  'Il dolce ogni tanto sta dentro al percorso.',
  'La tua nutrizionista è a un messaggio di distanza.',
  'Le feste durano un giorno, non una stagione.',
  'Le cose importanti raramente sono urgenti.',
  'Il lunedì non ha poteri magici.',
  'Tieni la frutta in vista.',
  'Sale, sonno e liquidi muovono la bilancia più del cibo.',
  'Va bene anche fare il minimo, oggi.',
  'Le abitudini buone si portano dietro le altre.',
  'Metti la musica e cammina.',
  'Continuare è già il risultato.',
  'Registrare i dati è utile anche quando non piacciono.',
  'Concentrati su oggi: domani non è ancora un problema.',
  'Scendi una fermata prima.',
  'I piccoli gesti di oggi sono i risultati di domani.',
  'Mangiare in piedi non conta come pranzo.',
  'Camminare dopo cena aiuta la digestione.',
  'Dieci minuti ci sono sempre.',
  'La sera, luci basse: il corpo capisce.',
  'Scegli con calma: anche quello è nutrimento.',
  'Si costruisce di giorno in giorno, non di colpo.',
  'Il primo passo è l\'unico difficile.',
  'La normalità è quello che fai il resto dei giorni.',
  'Il caffè del tardo pomeriggio si sente sul cuscino.',
  'Meno cose da decidere, più energie per quelle che contano.',
  'Le cose fatte sempre allo stesso modo costano meno fatica.',
  'Anche la testa ha bisogno di essere nutrita.',
  'Non è una dieta, è il tuo nuovo stile.',
  'Il cibo è anche piacere, non solo carburante.',
  'Non serve la palestra per muoversi.',
  'Sciogli le spalle: stanno lavorando da stamattina.',
  'Un dubbio scritto oggi è un problema in meno domani.',
  'La sveglia della sera vale quanto quella del mattino.',
  'Mangia quello che sceglieresti, non quello che avanza.',
  'Nessuno conosce il tuo corpo meglio di te.',
  'Fidati del piatto: è stato pensato per te.',
  'Cinque minuti stasera ti salvano il pranzo di domani.',
  'Un bicchiere d\'acqua adesso. Solo quello.',
  'Cucina una volta, mangia due volte.',
  'Il modo più semplice per iniziare è uscire di casa.',
  'Il telefono a tavola ti fa perdere metà del pasto.',
  'Il pane non è il nemico.',
  'Fai stretching mentre guardi la tv.',
  'L\'ambiente decide più delle intenzioni.',
  'D\'inverno il corpo chiede piatti caldi: scegli quelli giusti.',
  'La cucina pulita invita a cucinare.',
  'Nessuno lo fa alla perfezione. Davvero nessuno.',
  'Se la bilancia mette ansia, guardala meno spesso.',
  'In autogrill c\'è sempre un\'alternativa.',
  'Il piacere a tavola non è una debolezza.',
  'In vacanza il corpo si riposa: lascialo fare.',
  'Le ricette semplici sono quelle che si rifanno.',
  'Posa la forchetta tra un boccone e l\'altro.',
  'La cena della domenica esiste apposta.',
  'Fai una cosa alla volta: il resto aspetta.',
  'Quello che tieni in casa è quello che mangi.',
  'Un giorno normale vale quanto un giorno perfetto.',
  'Fai la spesa lo stesso giorno, ogni settimana.',
  'Puoi cambiare idea senza cambiare percorso.',
  'Sazi non vuol dire pieni.',
  'Un pasto non decide niente.',
  'Muoviti anche solo dieci minuti: contano.',
  'Le settimane contano più dei singoli giorni.',
  'Fidati del processo, ma continua a fare domande.',
  'A volte non è fame, è sete.',
  'Sbagliare fa parte del piano.',
  'Una routine della sera aiuta più di una sveglia in più.',
  'Un passo alla volta è comunque un passo avanti.',
  'Prepara la borsa la sera prima.',
  'Le cose si sentono prima nell\'energia che allo specchio.',
  'Un piano per la settimana toglie fatica alla testa.',
  'Il senso di colpa non ha mai aiutato nessuno.',
  'Condividi il percorso con chi ti sostiene, non con chi giudica.',
  'La pasta non è il nemico.',
  'Le giornate corte non sono una scusa, sono solo corte.',
  'Un centimetro in meno non si vede sulla bilancia.',
  'Bevi anche quando non hai caldo.',
  'Il tuo percorso non è il percorso di nessun altro.',
  'Quello che si ripete diventa facile.',
  'Raccontare come va aiuta chi ti segue a fare meglio.',
  'Il ritmo giusto è quello che riesci a tenere.',
  'I muscoli si ricordano di te più di quanto credi.',
  'Fai le cose in casa camminando, non correndo.',
  'Perfetto non esiste, e non serve.',
  'Cucinare insieme è più facile che cucinare da soli.',
  'Un piatto colorato è quasi sempre un piatto completo.',
  'Fai la cosa semplice, oggi. Domani si vedrà.',
  'Respira: tre respiri lenti cambiano la giornata.',
  'Non arrivare a tavola affamati: è lì che si esagera.',
  'Chiedere aiuto è una scelta intelligente.',
  'Il giudizio su di te, oggi, può saltare.',
  'L\'acqua non fa miracoli, ma aiuta tutto il resto.',
  'Il percorso è lungo apposta: c\'è tempo.',
  'Guarda il menu prima di sederti a tavola.',
  'Non contare sulla forza di volontà: contava poco anche ieri.',
  'Il caldo toglie appetito: non forzare, ma non saltare.',
  'Nessuno cambia abitudini in una settimana.',
  'Esci comunque: cinque minuti d\'aria cambiano l\'umore.',
  'Mangiare bene è più semplice di quanto raccontino.',
  'Il pisolino corto è un alleato, quello lungo no.',
  'Se cadi, ti rialzi. È solo questo.',
  'Le verdure surgelate valgono quelle fresche.',
  'La motivazione va e viene: le abitudini restano.',
  'Il movimento migliore è quello che ti piace fare.',
  'Cuoci di più e porta via il resto.',
  'Il sonno è metà del percorso.',
  'Non serve pesare tutto per mangiare bene.',
  'Una settimana ferma non è una settimana persa.',
  'Anche fermarsi è una fase, non un errore.',
  'L\'acqua è la cosa più semplice che puoi fare bene.',
  'Ci vuole pazienza, e la pazienza si allena.',
  'Se salti un pasto, non raddoppiare quello dopo.',
  'Non fare la spesa a stomaco vuoto.',
  'Chi si tratta bene va più lontano.',
  'Se lo fai a orario fisso, lo fai e basta.',
  'Se hai fame vera, mangia: non è un errore.',
  'Il caffè con gli amici vale più di mille rinunce.',
  'Misurati sempre nelle stesse condizioni.',
  'Metti la tavola: cambia come mangi.',
  'Il corpo ringrazia per ogni movimento, anche piccolo.',
  'Se qualcosa non ti torna, chiedi: è per questo che ci siamo.',
  'A tavola in famiglia si mangia meglio.',
  'Il corpo non è un nemico da controllare.',
  'Cucina quello che ti piace davvero.',
  'Guarda quanto è cambiata la giornata, non solo il numero.',
  'Un fine settimana fuori programma è solo un fine settimana.',
  'Il buonumore si allena come tutto il resto.',
  'Le occasioni restano occasioni: non diventano regola.',
  'Non confrontarti con nessun altro: i corpi sono diversi.',
  'Chi ti sta intorno impara guardando te.',
  'D\'estate si beve di più e si mangia più leggero.',
  'Bere acqua tra un bicchiere e l\'altro aiuta.',
  'In questo percorso c\'è una squadra con te.',
  'Si ricomincia al pasto dopo, non lunedì.',
  'Mangia con calma: la sazietà arriva dopo qualche minuto.',
  'L\'umore cambia, i tuoi motivi no.',
  'La routine non è noia: è risparmio di energie.',
  'Quello che fai spesso conta più di quello che fai bene.',
  'Compleanni e cene esistono: fanno parte della vita.',
  'Segnare le misure dà una memoria che la testa non ha.',
  'In viaggio si fa quello che si può, e va bene.',
  'Salta una volta, mai due di fila.',
  'Un piatto buono vale più di un piatto giusto.',
  'Non serve finire il piatto per forza.',
  'Il progresso non è una linea dritta.',
  'Cammina senza meta: serve anche quello.',
  'Metti le scarpe da ginnastica dove le vedi.',
  'Un\'abitudine nuova alla volta.',
  'Prima di riaprire il frigo, aspetta dieci minuti.',
  'Lo schermo la sera ruba sonno.',
  'Si può essere stanchi e continuare lo stesso.',
  'Una settimana storta non cancella un mese buono.',
  'Cambia una cosa sola e tienila per un mese.',
  'Il traguardo vero è non doverci più pensare.',
  'Il sonno arretrato non si recupera tutto, ma un po\' sì.',
  'Il pane in tavola si può anche allontanare.',
  'Dopo la festa si torna alla normalità, senza recuperi.',
  'Al bar un\'alternativa c\'è quasi sempre.',
  'Non devi meritarti il cibo.',
  'Fai la cosa difficile quando hai più energie.',
  'Il gusto conta: se non ti piace, non durerà.',
  'Cucinare per sé è un modo di volersi bene.',
  'Un frigo in ordine si apre con meno ansia.',
  'Non stai indietro: stai andando.',
  'Dimenticarsi di bere non è pigrizia: è abitudine.',
  'Alzarsi spesso conta quanto un allenamento.',
  'Aggancia l\'abitudine nuova a una che hai già.',
  'Un dato solo non è una tendenza.',
  'Quello che hai imparato resta anche quando finisce il piano.',
  'Il fine settimana è il momento migliore per muoversi di più.',
  'Un pasto speciale ogni tanto tiene in piedi tutto il resto.',
  'Il corpo tiene il conto di come lo tratti.',
  'Non tutti i giorni sono uguali, e va bene così.',
  'La stagione decide cosa è più buono: seguila.',
  'Pesarsi spesso serve solo se non ci si affeziona al numero.',
  'Meno rimproveri, più curiosità.',
  'Le porzioni si imparano con gli occhi.',
  'La spesa fatta bene è mezza settimana risolta.',
  'Il peso non racconta tutto quello che cambia.',
  'Il momento giusto è quello che scegli tu.',
  'Se esci a cena, esci a cena. Punto.',
  'A letto prima: è la scorciatoia più onesta che c\'è.',
  'Sposta la frutta al centro del tavolo.',
  'Fai spazio a una cosa bella, oggi.',
  'Il corpo si abitua: dagli tempo.',
  'Una passeggiata sistema anche i pensieri.',
  'Puoi dire no grazie senza spiegare niente.',
  'Le misure servono a capire, non a giudicare.',
  'Goditi quello che mangi: è tempo tuo.',
  'La costanza batte la perfezione.',
  'Muoversi la mattina resta addosso tutto il giorno.',
  'Cinque minuti di sole valgono un caffè.',
  'Se lo prepari, lo mangi.',
  'Non conta partire forte, conta restare.',
  'Il punto di partenza ormai è alle spalle.',
  'Chiedersi troppo è il modo più veloce per mollare.',
  'Se un dato sorprende, la prima cosa da fare è ripeterlo.',
  'Il tempo passa comunque: tanto vale usarlo.',
  'Acqua prima del caffè.',
  'Muoversi non è una punizione.',
];

/** Hash FNV-1a a 32 bit: stesso spirito di quello del catalogo i18n lato server. */
function hash32(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/** Passi coprimi con 360 → la sequenza di una cliente passa da tutte le frasi senza ripetere. */
const PASSI = [7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 49, 53, 59, 61];

/**
 * La frase di oggi per questa cliente. Stabile per tutto il giorno, diversa da cliente a
 * cliente, senza ripetizioni per 360 giorni.
 */
export function fraseDelGiorno(userId: string | null | undefined, now: Date = new Date()): string {
  // Giorni interi, contati sul calendario LOCALE del telefono: la frase cambia a mezzanotte
  // vera, ovunque sia la cliente. `Date.UTC` su anno/mese/giorno locali restituisce un multiplo
  // esatto di 86.400.000, quindi il conteggio non dipende dal fuso orario. (Provato: anche la
  // formulazione ingenua reggerebbe i cambi di ora legale — questa però dice cosa vogliamo
  // senza lasciare il dubbio a chi legge.)
  const giorno = Math.floor(Date.UTC(now.getFullYear(), now.getMonth(), now.getDate()) / 86_400_000);
  const h = hash32(userId || 'ospite');
  const passo = PASSI[h % PASSI.length]; // bit bassi
  const partenza = (h >>> 5) % FRASI_GAIA.length; // bit alti: indipendente dal passo
  return FRASI_GAIA[(partenza + giorno * passo) % FRASI_GAIA.length];
}
